name: spring-boot-demo-app
on: [workflow_dispatch, push]
jobs:
  demo-app-ci-ops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Maven Check
        run: |
          mvn --version
          java -version